#!/bin/bash

set -euo pipefail

AWG_SERVER_PORT="${AWG_SERVER_PORT:-55424}"
AWG_SUBNET_IP="${AWG_SUBNET_IP:-10.8.0.0}"
WIREGUARD_SUBNET_CIDR="${WIREGUARD_SUBNET_CIDR:-24}"
JUNK_PACKET_COUNT="${JUNK_PACKET_COUNT:-3}"
JUNK_PACKET_MIN_SIZE="${JUNK_PACKET_MIN_SIZE:-10}"
JUNK_PACKET_MAX_SIZE="${JUNK_PACKET_MAX_SIZE:-30}"
INIT_PACKET_JUNK_SIZE="${INIT_PACKET_JUNK_SIZE:-15}"
RESPONSE_PACKET_JUNK_SIZE="${RESPONSE_PACKET_JUNK_SIZE:-18}"
COOKIE_REPLY_PACKET_JUNK_SIZE="${COOKIE_REPLY_PACKET_JUNK_SIZE:-20}"
TRANSPORT_PACKET_JUNK_SIZE="${TRANSPORT_PACKET_JUNK_SIZE:-23}"
INIT_PACKET_MAGIC_HEADER="${INIT_PACKET_MAGIC_HEADER:-1020325451}"
RESPONSE_PACKET_MAGIC_HEADER="${RESPONSE_PACKET_MAGIC_HEADER:-3288052141}"
UNDERLOAD_PACKET_MAGIC_HEADER="${UNDERLOAD_PACKET_MAGIC_HEADER:-1766607858}"
TRANSPORT_PACKET_MAGIC_HEADER="${TRANSPORT_PACKET_MAGIC_HEADER:-2528465083}"

mkdir -p /opt/amnezia/awg
cd /opt/amnezia/awg

# Генерация ключей
WIREGUARD_SERVER_PRIVATE_KEY=$(awg genkey)
echo "$WIREGUARD_SERVER_PRIVATE_KEY" > /opt/amnezia/awg/wireguard_server_private_key.key

WIREGUARD_SERVER_PUBLIC_KEY=$(echo "$WIREGUARD_SERVER_PRIVATE_KEY" | awg pubkey)
echo "$WIREGUARD_SERVER_PUBLIC_KEY" > /opt/amnezia/awg/wireguard_server_public_key.key

WIREGUARD_PSK=$(awg genpsk)
echo "$WIREGUARD_PSK" > /opt/amnezia/awg/wireguard_psk.key

# Конфиг сервера awg0
cat > /opt/amnezia/awg/awg0.conf <<EOF
[Interface]
PrivateKey = ${WIREGUARD_SERVER_PRIVATE_KEY}
Address = ${AWG_SUBNET_IP}/${WIREGUARD_SUBNET_CIDR}
ListenPort = ${AWG_SERVER_PORT}
Jc = ${JUNK_PACKET_COUNT}
Jmin = ${JUNK_PACKET_MIN_SIZE}
Jmax = ${JUNK_PACKET_MAX_SIZE}
S1 = ${INIT_PACKET_JUNK_SIZE}
S2 = ${RESPONSE_PACKET_JUNK_SIZE}
S3 = ${COOKIE_REPLY_PACKET_JUNK_SIZE}
S4 = ${TRANSPORT_PACKET_JUNK_SIZE}
H1 = ${INIT_PACKET_MAGIC_HEADER}
H2 = ${RESPONSE_PACKET_MAGIC_HEADER}
H3 = ${UNDERLOAD_PACKET_MAGIC_HEADER}
H4 = ${TRANSPORT_PACKET_MAGIC_HEADER}
EOF

echo "AmneziaWG configured:"
echo "  Port:       ${AWG_SERVER_PORT}/udp"
echo "  Subnet:     ${AWG_SUBNET_IP}/${WIREGUARD_SUBNET_CIDR}"
echo "  Public key: ${WIREGUARD_SERVER_PUBLIC_KEY}"
